name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ZIP_NAME: app-bundle.zip
      BUCKET_NAME: your-bucket-name-1234
      REGION: ap-southeast-1
      EB_APP_NAME: your-eb-app
      EB_ENV_NAME: your-eb-env

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create deployment ZIP
        run: |
          zip -r $ZIP_NAME .ebextensions static templates app.py Procfile requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 Bucket (if not exists)
        run: |
          aws s3api create-bucket \
            --bucket $BUCKET_NAME \
            --region $REGION \
            --create-bucket-configuration LocationConstraint=$REGION || true

      - name: Upload to S3
        run: |
          aws s3 cp $ZIP_NAME s3://$BUCKET_NAME/$ZIP_NAME

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $EB_APP_NAME \
            --version-label v-${{ github.run_number }} \
            --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$ZIP_NAME

          aws elasticbeanstalk update-environment \
            --environment-name $EB_ENV_NAME \
            --version-label v-${{ github.run_number }}
