name: Deploy Flask to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ZIP_NAME: app-bundle.zip

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create deployment ZIP
        run: |
          zip -r $ZIP_NAME \
            .ebextensions \
            static \
            templates \
            app.py \
            Procfile \
            requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp $ZIP_NAME s3://${{ secrets.S3_BUCKET_NAME }}/$ZIP_NAME

      - name: Gawe Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "v-${{ github.run_number }}" \
            --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=$ZIP_NAME

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "v-${{ github.run_number }}" \
            --option-settings \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=FLASK_ENV,Value=production \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=SECRET_API_KEY,Value=${{ secrets.PORT }}